# Generated by Django 2.2.7 on 2020-07-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropdown1', models.CharField(choices=[('ch', 'Choose'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=3)),
                ('form_id', models.CharField(max_length=100, unique=True)),
                ('dropdown2', models.CharField(choices=[('ch', 'Choose'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=3)),
                ('checkbox1', models.BooleanField()),
                ('Integerbox', models.IntegerField()),
                ('textbox', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField()),
                ('newcheckbox1', models.BooleanField()),
                ('newcheckbox2', models.BooleanField()),
                ('newcheckboxA', models.BooleanField()),
                ('newcheckboxB', models.BooleanField()),
                ('newcheckboxC', models.BooleanField()),
                ('newcheckboxD', models.BooleanField()),
                ('IntegertextA', models.IntegerField()),
                ('IntegertextB', models.IntegerField()),
                ('IntegertextC', models.IntegerField()),
                ('IntegertextD', models.IntegerField()),
            ],
        ),
    ]
