# Generated by Django 2.2.7 on 2020-07-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='Integerbox',
            new_name='Integer_box',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='checkbox1',
            new_name='check_box_1',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='dropdown1',
            new_name='drop_down_1',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='dropdown2',
            new_name='drop_down_2',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='newcheckbox1',
            new_name='new_check_box_1',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='newcheckbox2',
            new_name='new_check_box_2',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='IntegertextA',
            new_name='new_check_box_A',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='IntegertextB',
            new_name='new_check_box_B',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='IntegertextC',
            new_name='new_check_box_C',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='IntegertextD',
            new_name='new_check_box_D',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='textbox',
            new_name='text_box',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='newcheckboxA',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='newcheckboxB',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='newcheckboxC',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='newcheckboxD',
        ),
    ]
